"""Report generator - exports analysis results to PDF, PPTX, DOCX."""

import os
from jinja2 import Template

# PDF template
PDF_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body { font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; color: #333; line-height: 1.6; }
    h1 { color: #1a1a2e; border-bottom: 3px solid #e94560; padding-bottom: 10px; }
    h2 { color: #16213e; margin-top: 30px; }
    h3 { color: #0f3460; }
    .stat-box { background: #f8f9fa; border-left: 4px solid #e94560; padding: 15px; margin: 15px 0; }
    .stat-number { font-size: 2em; font-weight: bold; color: #e94560; }
    .sentiment-positive { color: #27ae60; }
    .sentiment-negative { color: #e74c3c; }
    .sentiment-neutral { color: #95a5a6; }
    .section { margin-bottom: 30px; page-break-inside: avoid; }
    pre { background: #f4f4f4; padding: 15px; border-radius: 5px; white-space: pre-wrap; font-size: 0.9em; }
    .footer { margin-top: 50px; text-align: center; color: #999; font-size: 0.8em; }
</style>
</head>
<body>
    <h1>Reddit Brand Analysis Report</h1>
    <p><strong>Brand:</strong> {{ keyword }} | <strong>Date:</strong> {{ date }}</p>

    <div class="section">
        <h2>Overview</h2>
        <div class="stat-box">
            <span class="stat-number">{{ total_posts }}</span> posts analyzed |
            Avg Sentiment: <span class="sentiment-{{ sentiment_class }}">{{ avg_sentiment }}</span>
        </div>
        {% if sentiment_distribution %}
        <p>Positive: {{ sentiment_distribution.get('positive', 0) }}% |
           Neutral: {{ sentiment_distribution.get('neutral', 0) }}% |
           Negative: {{ sentiment_distribution.get('negative', 0) }}%</p>
        {% endif %}
    </div>

    <div class="section">
        <h2>Hot Posts Analysis</h2>
        <pre>{{ hot_posts_text }}</pre>
    </div>

    <div class="section">
        <h2>Topic Clusters</h2>
        <pre>{{ topics_text }}</pre>
    </div>

    <div class="section">
        <h2>Subreddit Profiles</h2>
        <pre>{{ subreddit_text }}</pre>
    </div>

    <div class="section">
        <h2>Marketing Strategy & Recommendations</h2>
        <pre>{{ marketing_text }}</pre>
    </div>

    <div class="footer">
        Generated by Reddit Marketing Tool | {{ date }}
    </div>
</body>
</html>
"""


class ReportGenerator:
    """Generates PDF, PPTX, and DOCX reports from analysis data."""

    def _extract_texts(self, data: dict) -> dict:
        """Extract text content from analysis data."""
        return {
            "hot_posts_text": (data.get("hot_posts") or {}).get("raw", "No data"),
            "topics_text": (data.get("top_topics") or {}).get("raw", "No data"),
            "subreddit_text": (data.get("subreddit_breakdown") or {}).get("profiles", "No data"),
            "marketing_text": (data.get("marketing_advice") or {}).get("raw", "No data"),
            "sentiment_class": self._sentiment_class(data.get("avg_sentiment", 0)),
        }

    def _sentiment_class(self, score) -> str:
        if score and score >= 0.05:
            return "positive"
        elif score and score <= -0.05:
            return "negative"
        return "neutral"

    def generate_pdf(self, data: dict, output_dir: str, filename: str) -> str:
        """Generate a PDF report using WeasyPrint."""
        from weasyprint import HTML

        texts = self._extract_texts(data)
        template = Template(PDF_TEMPLATE)
        html_content = template.render(
            keyword=data["keyword"],
            date=data["date"],
            total_posts=data.get("total_posts", 0),
            avg_sentiment=data.get("avg_sentiment", "N/A"),
            sentiment_distribution=data.get("sentiment_distribution"),
            **texts,
        )

        filepath = os.path.join(output_dir, f"{filename}.pdf")
        HTML(string=html_content).write_pdf(filepath)
        return filepath

    def generate_pptx(self, data: dict, output_dir: str, filename: str) -> str:
        """Generate a PPTX presentation."""
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN

        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        texts = self._extract_texts(data)

        # Slide 1: Title
        slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank layout
        self._add_dark_bg(slide, prs)
        title_box = slide.shapes.add_textbox(Inches(1), Inches(2), Inches(11), Inches(2))
        tf = title_box.text_frame
        p = tf.paragraphs[0]
        p.text = f"Reddit Brand Analysis"
        p.font.size = Pt(44)
        p.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        p.font.bold = True
        p.alignment = PP_ALIGN.CENTER

        subtitle_box = slide.shapes.add_textbox(Inches(1), Inches(4), Inches(11), Inches(1))
        tf = subtitle_box.text_frame
        p = tf.paragraphs[0]
        p.text = f"{data['keyword']} | {data['date']}"
        p.font.size = Pt(24)
        p.font.color.rgb = RGBColor(0xE9, 0x45, 0x60)
        p.alignment = PP_ALIGN.CENTER

        # Slide 2: Overview
        self._add_content_slide(prs, "Overview", [
            f"Total Posts Analyzed: {data.get('total_posts', 0)}",
            f"Average Sentiment: {data.get('avg_sentiment', 'N/A')}",
            f"Sentiment: Positive {(data.get('sentiment_distribution') or {}).get('positive', 0)}% | "
            f"Neutral {(data.get('sentiment_distribution') or {}).get('neutral', 0)}% | "
            f"Negative {(data.get('sentiment_distribution') or {}).get('negative', 0)}%",
        ])

        # Slide 3-6: Analysis sections
        sections = [
            ("Hot Posts Analysis", texts["hot_posts_text"]),
            ("Topic Clusters", texts["topics_text"]),
            ("Subreddit Profiles", texts["subreddit_text"]),
            ("Marketing Strategy", texts["marketing_text"]),
        ]
        for title, content in sections:
            self._add_content_slide(prs, title, content.split("\n")[:20])

        filepath = os.path.join(output_dir, f"{filename}.pptx")
        prs.save(filepath)
        return filepath

    def _add_dark_bg(self, slide, prs):
        """Add dark background to slide."""
        from pptx.util import Inches
        from pptx.dml.color import RGBColor

        bg = slide.shapes.add_shape(
            1, Inches(0), Inches(0),
            prs.slide_width, prs.slide_height,
        )
        bg.fill.solid()
        bg.fill.fore_color.rgb = RGBColor(0x1A, 0x1A, 0x2E)
        bg.line.fill.background()
        # Send to back
        slide.shapes._spTree.remove(bg._element)
        slide.shapes._spTree.insert(2, bg._element)

    def _add_content_slide(self, prs, title: str, content_lines: list):
        """Add a content slide with title and bullet points."""
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor

        slide = prs.slides.add_slide(prs.slide_layouts[6])
        self._add_dark_bg(slide, prs)

        # Title
        title_box = slide.shapes.add_textbox(Inches(0.8), Inches(0.5), Inches(11), Inches(1))
        tf = title_box.text_frame
        p = tf.paragraphs[0]
        p.text = title
        p.font.size = Pt(32)
        p.font.color.rgb = RGBColor(0xE9, 0x45, 0x60)
        p.font.bold = True

        # Content
        content_box = slide.shapes.add_textbox(Inches(0.8), Inches(1.8), Inches(11.5), Inches(5))
        tf = content_box.text_frame
        tf.word_wrap = True

        for i, line in enumerate(content_lines):
            if not line.strip():
                continue
            if i == 0:
                p = tf.paragraphs[0]
            else:
                p = tf.add_paragraph()
            p.text = line.strip()[:200]
            p.font.size = Pt(14)
            p.font.color.rgb = RGBColor(0xDD, 0xDD, 0xDD)

    def generate_docx(self, data: dict, output_dir: str, filename: str) -> str:
        """Generate a DOCX document."""
        from docx import Document
        from docx.shared import Pt, RGBColor

        doc = Document()

        # Title
        title = doc.add_heading(f"Reddit Brand Analysis: {data['keyword']}", level=0)
        doc.add_paragraph(f"Report Date: {data['date']}")
        doc.add_paragraph("")

        # Overview
        doc.add_heading("Overview", level=1)
        doc.add_paragraph(f"Total Posts Analyzed: {data.get('total_posts', 0)}")
        doc.add_paragraph(f"Average Sentiment Score: {data.get('avg_sentiment', 'N/A')}")
        dist = data.get("sentiment_distribution") or {}
        doc.add_paragraph(
            f"Sentiment Distribution: Positive {dist.get('positive', 0)}% | "
            f"Neutral {dist.get('neutral', 0)}% | Negative {dist.get('negative', 0)}%"
        )

        texts = self._extract_texts(data)

        # Sections
        sections = [
            ("Hot Posts Analysis", texts["hot_posts_text"]),
            ("Topic Clusters", texts["topics_text"]),
            ("Subreddit Profiles", texts["subreddit_text"]),
            ("Marketing Strategy & Recommendations", texts["marketing_text"]),
        ]

        for title, content in sections:
            doc.add_heading(title, level=1)
            for para in content.split("\n"):
                if para.strip():
                    doc.add_paragraph(para.strip())

        # Footer
        doc.add_paragraph("")
        footer = doc.add_paragraph("Generated by Reddit Marketing Tool")
        footer.runs[0].font.size = Pt(8)
        footer.runs[0].font.color.rgb = RGBColor(0x99, 0x99, 0x99)

        filepath = os.path.join(output_dir, f"{filename}.docx")
        doc.save(filepath)
        return filepath
